group 'com.adpopcorn.adpopcornreward'
version '1.0'
apply plugin: 'com.android.library'

android {
    compileSdk 35
    namespace 'com.adpopcorn.adpopcornreward'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
        targetSdk 35
    }
}

dependencies {
    implementation 'com.igaworks.offerwall:AdPopcornOfferwall:9.2.7'
}

